

def helper():
    print("")
    print("")
    print("")
    print("*"*30)
    print("")
    print("Webrute - Enumerting directories and files tool")
    print("")
    print("*"*30)
    print("")
    print("         ==> USAGE MANUAL <==")
    print("")
    print("Full Syntax : -t threads -u target_url -w wordlist_path -r word -a user_agent -R  extensions")
    print("")
    print("-t --threads")
    print("     Number of threads to utilize")
    print("-u --url==target_url")
    print("      Specify target url")
    print("-w --wordlist==wordlist_path")
    print("     Path for the wordlist to use")
    print("-r --resume=word")
    print("     Specify a word of the wordlist from which you want start the brute forcing")
    print("-a --useragent=user_agent")
    print("     Specify a user agent to do request")
    print("-R --recursive")
    print("     Enable recursive directory brute forcing only for directory returning 200 as response status code ")
    print("")
    print("You can replace 'extensions' to define the extensions set you want use during brute forcing.")
    print("Please, make sure you define extensions after all other flags that you want to use.")
    print("")
    print("")
    print("-"*30)
    print("")
    print("examples: ")
    print("")
    print("Running webrute with default settings : python3 webrute.py")
    print("")
    print("Full syntax : python3 webrute.py -t 10 -u http://testaspnet.vulnweb.com -w /tmp/wordlist.txt -r install.txt -a Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 -R .bak .php")
    print("")
    print("-"*30)
    print("")
    print("The following are the default parameter values : ")
    print("")
    print("--threads = 5")
    print("--url = http://testaspnet.vulnweb.com" )
    print("--wordlist_path = /tmp/wordlist.txt ")
    print("--resume is not defined by default")
    print("--auseragent = Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0")
    print("--recursive = True")
    print("")
    print("No extensions by default. You can specify extensions at the end of command line.")



